generatorName: typescript-fetch
inputSpec: ./schema/openapispec-upsun.json
outputDir: ./
packageName: upsun-client
templateDir: ./templates/node
generateSupportingFiles: true
verbose: false
generateAliasAsModel: true
apiTests: true
modelTests: true
apiDocs: false
modelDocs: false
authMethods:
isOAuth: true

nameMappings:
  _transactions: _transactionsFilter

parameterNameMappings:
  _transactions: _transactions

additionalProperties:
  isApiKey: true
  sdkName: upsun-sdk-node
  sdkVersion: 0.6.0
  sdkDescription: The official Upsun SDK for Node.js
  licenseName: Apache-2.0
  artifactUrl: https://github.com/upsun/upsun-sdk-node
  authorName: Mickael GAILLARD
  contributors: |
    [
        {
            "name": "Mickael GAILLARD",
            "email": "mickael.gaillard@upsun.com"
        },
        {
            "name": "Florent HUCK",
            "email": "florent.huck@upsun.com"
        },
        {
            "name": "Upsun Advocacy Team",
            "homepage": "https://www.upsun.com"
        }
      ],
  importFileExtension: .js
  apiPackage: src/api
  modelPackage: src/model
  #Bug on OpenApiGenerator => fileNaming: kebab-case
  enumPropertyNaming: UPPERCASE
  modelPropertyNaming: camelCase
  paramNaming: camelCase
  supportsES6: true
  withInterfaces: true

files:
  apis.mustache:
    templateType: API
    destinationFilename: .ts
    folder: src/api
  apis.index.mustache:
    templateType: SupportingFiles
    destinationFilename: index.ts
    folder: src/api
  models.mustache:
    templateType: Model
    destinationFilename: .ts
    folder: src/model
  models.index.mustache:
    templateType: SupportingFiles
    destinationFilename: index.ts
    folder: src/model
  runtime.mustache:
    templateType: SupportingFiles
    destinationFilename: runtime.ts
    folder: src/core