#!/bin/bash

echo ""
echo "  build              - Compile TypeScript files to JavaScript"
echo "  build:watch        - Watch mode compilation"
echo "  clean              - Remove dist directory"
echo "  fix:all            - Run all linters and formatters in fix mode"
echo "  fix:es             - Fix ESLint issues"
echo "  fix:prettier       - Format code with Prettier"
echo "  lint:all           - Run all linters"
echo "  lint:es            - Check ESLint errors"
echo "  lint:prettier      - Check code formatting"
echo "  qa                 - Run linting and tests"
echo "  qa:all             - Full build, lint and test pipeline"
echo "  run                - Execute the compiled app"
echo "  spec:clean         - Clean generated API and model files"
echo "  spec:dl            - Download OpenAPI spec"
echo "  spec:generate      - Generate API from OpenAPI spec"
echo "  spec:patch         - Apply patches to OpenAPI spec"
echo "  test               - Run unit tests"
echo "  test:all           - Run all unit tests"
echo "  test:coverage      - Generate test coverage report"
echo "  test:coverage:ci   - CI coverage report"
echo "  test:integration   - Run integration tests"
echo "  test:watch         - Watch mode for tests"
echo ""
